### ISSUE TITLE
method by which to maintain elasticsearch.yml

### ISSUE THREAD

**Issue by jamesbeedy** [jamesbeedy/layer-elasticsearch#4]
@sebastienpattyn93 check out how the config is maintained in the [redis charm ](http://bazaar.launchpad.net/~charmers/charms/trusty/redis/trunk/files)

I recently took a stab at rewriting the redis charm [here](https://github.com/jamesbeedy/juju-charm-redis), and realized there is some value to caching and backing up the config as is done in the legacy redis.

Not sure how we should move forward with this, as it seems to need to be maintained separately on a per-node basis, not sure we should have it in the base layer even.

Thoughts?

**Comment by jamesbeedy** [comment]
@marcoceppi @chuckbutler @kwmonroe ^^

**Comment by chuckbutler** [comment]
Depends on how the config is being put together. This is kind of generic. Could you perhaps narrow it down to specifically what you're referring to? Such as:

Cache the data coming from peer nodes in unitdata during the *-relation-changed hook events.

Or leadership based data.

But if values are coming from config and on the wire during a relationship, I tend to prefer to use the current values coming from those sources, so it helps to mitigate stale config keeping the service working even though its completely misconfigured by the current relationship(s). Its a balance of when to grab from what we're already caching, and when to cache the cache, which is a bit tricky.

Remember that reactive keeps a solid cache of data in a system-use-only of the charms unitdata, and can be viewed using the chlp/sqlite-cli commands to fetch data from that sql lite database. 

Hope this helps.

**Comment by jamesbeedy** [comment]
#9 fixes
